#  Gispo Ltd., hereby disclaims all copyright interest in the program NLSgpkgloadert
#  Copyright (C) 2018-2020 Gispo Ltd (https://www.gispo.fi/).
#
#
#  This file is part of NLSgpkgloadert.
#
#  NLSgpkgloadert is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  NLSgpkgloadert is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with NLSgpkgloadert.  If not, see <https://www.gnu.org/licenses/>.

MTK_ALL_PRODUCTS_URL = (
    "https://tiedostopalvelu.maanmittauslaitos.fi/tp/feed/mtp/maastotietokanta/kaikki"
)
MTK_ALL_PRODUCTS_DOWNLOAD_URL = (
    "https://tiedostopalvelu.maanmittauslaitos.fi/tp/"
    "tilauslataus/tuotteet/maastotietokanta/kaikki"
)
MTK_LAYERS_KEY_PREFIX = "MTK"
MTK_ALL_PRODUCTS_TITLE = "Maastotietokanta, kaikki kohteet"
MTK_PRODUCT_NAMES = [
    "YhteisetTyypit",
    "Aallonmurtaja",
    "AidanSymboli",
    "Aita",
    "Allas",
    "AluemerenUlkoraja",
    "AmpumaAlue",
    "Ankkuripaikka",
    "Autoliikennealue",
    "HarvaLouhikko",
    "Hautausmaa",
    "Hietikko",
    "Hylky",
    "HylynSyvyys",
    "IlmaradanKannatinpylvas",
    "Ilmarata",
    "Jyrkanne",
    "Kaatopaikka",
    "Kaislikko",
    "KallioAlue",
    "KallioSymboli",
    "Kalliohalkeama",
    "Kansallispuisto",
    "Karttasymboli",
    "Kellotapuli",
    "Kivi",
    "Kivikko",
    "Korkeuskayra",
    "KorkeuskayranKorkeusarvo",
    "Koski",
    "KunnanHallintokeskus",
    "KunnanHallintoraja",
    "Kunta",
    "Lahde",
    "Lahestymisvalo",
    "Lentokenttaalue",
    "Louhos",
    "Luiska",
    "Luonnonpuisto",
    "Luonnonsuojelualue",
    "MaaAineksenottoalue",
    "Maasto2kuvionReuna",
    "MaastokuvionReuna",
    "Maatalousmaa",
    "MaatuvaVesialue",
    "Masto",
    "MastonKorkeus",
    "Matalikko",
    "Meri",
    "MerkittavaLuontokohde",
    "MetsamaanKasvillisuus",
    "MetsamaanMuokkaus",
    "MetsanRaja",
    "Muistomerkki",
    "Muuntaja",
    "Muuntoasema",
    "Nakotorni",
    "Niitty",
    "Osoitepiste",
    "Paikannimi",
    "Pato",
    "Pelastuskoodipiste",
    "PistolaituriViiva",
    "Portti",
    "Puisto",
    "PutkijohdonSymboli",
    "Putkijohto",
    "Puu",
    "Puurivi",
    "RajavyohykkeenTakaraja",
    "Rakennelma",
    "Rakennus",
    "Rakennusreunaviiva",
    "Rautatie",
    "Rautatieliikennepaikka",
    "RautatienSymboli",
    "Retkeilyalue",
    "Sahkolinja",
    "SahkolinjanSymboli",
    "Savupiippu",
    "SavupiipunKorkeus",
    "Selite",
    "SisaistenAluevesienUlkoraja",
    "Soistuma",
    "Sulkuportti",
    "Suo",
    "SuojaAlue",
    "SuojaAlueenReunaviiva",
    "Suojametsa",
    "Suojanne",
    "SuojelualueenReunaviiva",
    "SuurjannitelinjanPylvas",
    "Syvyyskayra",
    "SyvyyskayranSyvyysarvo",
    "Syvyyspiste",
    "TaajaanRakennettuAlue",
    "TaajaanRakennetunAlueenReuna",
    "Taytemaa",
    "Tervahauta",
    "Tiesymboli",
    "Tienroteksti",
    "Tieviiva",
    "Tulentekopaikka",
    "TulvaAlue",
    "TunnelinAukko",
    "Turvalaite",
    "Tuulivoimala",
    "Uittolaite",
    "Uittoranni",
    "UlkoJaSisasaaristonRaja",
    "UrheiluJaVirkistysalue",
    "ValtakunnanRajapyykki",
    "Varastoalue",
    "Vedenottamo",
    "VedenpinnanKorkeusluku",
    "Vesiasteikko",
    "Vesikivi",
    "Vesikivikko",
    "Vesikulkuvayla",
    "VesikulkuvaylanKulkusuunta",
    "VesikulkuvaylanTeksti",
    "Vesikuoppa",
    "Vesitorni",
    "Viettoviiva",
    "Virtausnuoli",
    "VirtavesiKapea",
    "VirtavesiAlue",
    "Jarvi",
]

MTK_STYLED_LAYERS = [
    "Vesitorni",
    "Tuulivoimala",
    "Savupiippu",
    "Nakotorni",
    "Masto",
    "Vesikuoppa",
    "Vedenottamo",
    "Lahde",
    "TunnelinAukko",
    "Selite",
    "MetsamaanKasvillisuus",
    "Kivi",
    "Kaislikko",
    "HarvaLouhikko",
    "Paikannimi",
    "Rakennelma",
    "Tieviiva",
    "Rautatie",
    "Sahkolinja",
    "Aita",
    "Aallonmurtaja",
    "PistolaituriViiva",
    "Luiska",
    "Jyrkanne",
    "VirtavesiKapea",
    "KorkeuskayranKorkeusarvo",
    "Korkeuskayra",
    "AmpumaAlue",
    "SuojaAlue",
    "Luonnonsuojelualue",
    "Kansallispuisto",
    "Kunta",
    "TaajaanRakennettuAlue",
    "Rakennus",
    "Varastoalue",
    "Autoliikennealue",
    "Lentokenttaalue",
    "UrheiluJaVirkistysalue",
    "Hautausmaa",
    "MaaAineksenottoalue",
    "Maatalousmaa",
    "Puisto",
    "Niitty",
    "TulvaAlue",
    "MaatuvaVesialue",
    "Soistuma",
    "Suo",
    "Taytemaa",
    "Kivikko",
    "KallioAlue",
    "Hietikko",
    "Jarvi",
    "Allas",
    "VirtavesiAlue",
    "Meri",
]
