# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NLSGeoPackageLoader
                                 A QGIS plugin
 This plugin downloads data from NLS and creates a GeoPackage
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-03-02
        copyright            : (C) 2019 by Gispo Oy
        email                : mikael@gispo.fi
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NLSGeoPackageLoader class from file NLSGeoPackageLoader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .nls_geopackage_loader import NLSGeoPackageLoader
    return NLSGeoPackageLoader(iface)
