# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NLSGeoPackageLoader
                                 A QGIS plugin
 This plugin downloads data from NLS and creates a GeoPackage
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-03-02
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Gispo Oy
        email                : mikael@gispo.fi
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
import io
import zipfile
import xml.etree.ElementTree
import requests

from qgis.core import QgsVectorLayer, QgsMessageLog, QgsProject, QgsFeatureRequest, QgsVectorFileWriter, QgsProcessingFeedback
from qgis.gui import QgsBusyIndicatorDialog, QgsFileWidget
from osgeo import ogr

from PyQt5 import uic
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication, QTimer
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction, QMessageBox, QListWidgetItem

import processing

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .nls_geopackage_loader_dialog import NLSGeoPackageLoaderDialog

NLS_USER_KEY_DIALOG_FILE = "nls_geopackage_loader_dialog_NLS_user_key.ui"
MUNICIPALITIES_DIALOG_FILE = "nls_geopackage_loader_dialog_municipality_selection.ui"

MTK_ALL_PRODUCTS_URL = "https://tiedostopalvelu.maanmittauslaitos.fi/tp/feed/mtp/maastotietokanta/kaikki"
MTK_ALL_PRODUCTS_DOWNLOAD_URL = "https://tiedostopalvelu.maanmittauslaitos.fi/tp/tilauslataus/tuotteet/maastotietokanta/kaikki"
MTK_LAYERS_KEY_PREFIX = "MTK"
MTK_ALL_PRODUCTS_TITLE = "Maastotietokanta, kaikki kohteet"
MTK_PRODUCT_NAMES_PREFIX = "Maastotietokanta, "
MTK_PRODUCT_NAMES = ["YhteisetTyypit", "Aallonmurtaja", "AidanSymboli", "Aita", "Allas", "AluemerenUlkoraja", "AmpumaAlue",
                     "Ankkuripaikka", "Autoliikennealue", "HarvaLouhikko", "Hautausmaa", "Hietikko", "Hylky", "HylynSyvyys",
                     "IlmaradanKannatinpylvas", "Ilmarata", "Jyrkanne", "Kaatopaikka", "Kaislikko", "KallioAlue", "KallioSymboli",
                     "Kalliohalkeama", "Kansallispuisto", "Karttasymboli", "Kellotapuli", "Kivi", "Kivikko", "Korkeuskayra",
                     "KorkeuskayranKorkeusarvo", "Koski", "KunnanHallintokeskus", "KunnanHallintoraja", "Kunta", "Lahde",
                     "Lahestymisvalo", "Lentokenttaalue", "Louhos", "Luiska", "Luonnonpuisto", "Luonnonsuojelualue",
                     "MaaAineksenottoalue", "Maasto2kuvionReuna", "MaastokuvionReuna", "Maatalousmaa", "MaatuvaVesialue",
                     "Masto", "MastonKorkeus", "Matalikko", "MerkittavaLuontokohde", "MetsamaanKasvillisuus", "MetsamaanMuokkaus",
                     "MetsanRaja", "Muistomerkki", "Muuntaja", "Muuntoasema", "Nakotorni", "Niitty", "Osoitepiste", "Paikannimi",
                     "Pato", "Pelastuskoodipiste", "PistolaituriViiva", "Portti", "Puisto", "PutkijohdonSymboli", "Putkijohto",
                     "Puu", "Puurivi", "RajavyohykkeenTakaraja", "Rakennelma", "Rakennus", "Rakennusreunaviiva", "Rautatie",
                     "Rautatieliikennepaikka", "RautatienSymboli", "Retkeilyalue", "Sahkolinja", "SahkolinjanSymboli", "Savupiippu",
                     "SavupiipunKorkeus", "Selite", "SisaistenAluevesienUlkoraja", "Soistuma", "Sulkuportti", "Suo", "SuojaAlue",
                     "SuojaAlueenReunaviiva", "Suojametsa", "Suojanne", "SuojelualueenReunaviiva", "SuurjannitelinjanPylvas",
                     "Syvyyskayra", "SyvyyskayranSyvyysarvo", "Syvyyspiste", "TaajaanRakennettuAlue", "TaajaanRakennetunAlueenReuna",
                     "Taytemaa", "Tervahauta", "Tiesymboli", "Tienroteksti", "Tieviiva", "Tulentekopaikka", "TulvaAlue",
                     "TunnelinAukko", "Turvalaite", "Tuulivoimala", "Uittolaite", "Uittoranni", "UlkoJaSisasaaristonRaja",
                     "UrheiluJaVirkistysalue", "ValtakunnanRajapyykki", "Varastoalue", "Vedenottamo", "VedenpinnanKorkeusluku",
                     "Vesiasteikko", "Vesikivi", "Vesikivikko", "Vesikulkuvayla", "VesikulkuvaylanKulkusuunta", "VesikulkuvaylanTeksti",
                     "Vesikuoppa", "Vesitorni", "Viettoviiva", "Virtausnuoli", "VirtavesiKapea", "VirtavesiAlue"]
MTK_PRESELECTED_PRODUCTS = ["Maastotietokanta, Tieviiva", "Maastotietokanta, Puisto", "Maastotietokanta, Maastotietokanta, Maastotietokanta, Maastotietokanta, Vesitorni"]

class NLSGeoPackageLoader:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'NLSGeoPackageLoader_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&NLS GeoPackage Downloader')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        self.initWithNLSData()

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('NLSGeoPackageLoader', message)


    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/nls_geopackage_loader/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'NLS GeoPackage Downloader'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&NLS GeoPackage Downloader'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        self.nls_user_key = QSettings().value("/NLSgpkgloader/userKey", "", type=str)
        self.data_download_dir = QSettings().value("/NLSgpkgloader/dataDownloadDir", "", type=str)
        self.addDownloadedDataAsLayer = QSettings().value("/NLSgpkgloader/addDownloadedDataAsLayer", True, type=bool)
        self.showMunicipalitiesAsLayer = QSettings().value("/NLSgpkgloader/showMunicipalitiesAsLayer", True, type=bool)
        self.showUTMGridsAsLayer = QSettings().value("/NLSgpkgloader/showUTMGridsAsLayer", False, type=bool)

        if self.nls_user_key == "":
            self.showSettingsDialog()

        self.loadLayers()

        self.product_types = self.downloadNLSProductTypes()

        self.municipalities_dialog = uic.loadUi(os.path.join(self.path, MUNICIPALITIES_DIALOG_FILE))
        self.municipalities_dialog.settingsPushButton.clicked.connect(self.showSettingsDialog)

        iter = self.municipality_layer.getFeatures()
        for feature in iter:
            item = QListWidgetItem(feature['NAMEFIN'])
            self.municipalities_dialog.municipalityListWidget.addItem(item)

        for key, value in list(self.product_types.items()):
            item = QListWidgetItem(value)
            self.municipalities_dialog.productListWidget.addItem(item)
            if value in MTK_PRESELECTED_PRODUCTS:
                self.municipalities_dialog.productListWidget.setCurrentItem(item)

        self.municipalities_dialog.show()

        result = self.municipalities_dialog.exec_()

        if result:
            #self.mun_utm5_features = []
            #self.mun_utm10_features = []
            self.mun_utm25lr_features = []
            #self.mun_utm25_features = []
            #self.mun_utm50_features = []
            #self.mun_utm100_features = []
            #self.mun_utm200_features = []

            self.newFile = True # TODO: move somewhere else and create an option for the user
            self.fileName = self.municipalities_dialog.fileNameEdit.text().strip()
            if self.fileName == "":
                QMessageBox.critical(self.iface.mainWindow(), self.tr(u'Invalid filename'), self.tr(u'Please enter a valid filename'))
                return
            if self.fileName.split('.')[-1].lower() != 'gpkg':
                self.fileName += '.gpkg'

            selected_mun_names = []
            for item in self.municipalities_dialog.municipalityListWidget.selectedItems():
                selected_mun_names.append(item.text())

            QgsMessageLog.logMessage(str(selected_mun_names), 'NLSgpkgloader', 0)

            product_types = {} # TODO ask from the user via dialog that lists types based on NLS Atom service

            self.selected_mtk_product_types = []

            for selected_prod_title in self.municipalities_dialog.productListWidget.selectedItems():
                for key, value in list(self.product_types.items()):
                    if selected_prod_title.text() == value:
                        if key.startswith(MTK_LAYERS_KEY_PREFIX): # Individual MTK layer
                            self.selected_mtk_product_types.append(selected_prod_title.text()[len(MTK_PRODUCT_NAMES_PREFIX):])
                            product_types[MTK_ALL_PRODUCTS_URL] = MTK_ALL_PRODUCTS_TITLE
                        else:
                            product_types[key] = value

            QgsMessageLog.logMessage(str(product_types), 'NLSgpkgloader', 0)
            QgsMessageLog.logMessage(str(self.selected_mtk_product_types), 'NLSgpkgloader', 0)

            if len(product_types) > 0: # TODO: check if len(selected_municipalities) > 0 OR len(selected_features) > 0
                self.busy_indicator_dialog = QgsBusyIndicatorDialog(self.tr(u'A moment... downloaded 0% of the files '), self.iface.mainWindow())
                self.busy_indicator_dialog.show()
                QCoreApplication.processEvents()
                self.mun_utm25lr_features = []

                self.mun_utm25lr_features = self.getMunicipalityIntersectingFeatures(selected_mun_names, self.utm25lr_layer)

                #for selected_mun_name in selected_mun_names:
                    #self.mun_utm10_features = self.getMunicipalityIntersectingFeatures(selected_mun_name, self.utm10_layer)
                    #self.mun_utm25lr_features = self.getMunicipalityIntersectingFeatures(selected_mun_name, self.utm25lr_layer)
                    #self.mun_utm25_features = self.getMunicipalityIntersectingFeatures(selected_mun_name, self.utm25_layer)
                    #self.mun_utm50_features = self.getMunicipalityIntersectingFeatures(selected_mun_name, self.utm50_layer)
                    #self.mun_utm100_features = self.getMunicipalityIntersectingFeatures(selected_mun_name, self.utm100_layer)
                    #self.mun_utm200_features = self.getMunicipalityIntersectingFeatures(selected_mun_name, self.utm200_layer)

                self.downloadData(product_types)

    def loadLayers(self):
        '''Load municipality and map tile layers'''
        self.municipality_layer = QgsVectorLayer(os.path.join(self.path, "data/SuomenKuntajako_2018_10k.shp"), "municipalities", "ogr")
        if not self.municipality_layer.isValid():
            QgsMessageLog.logMessage('Failed to load the municipality layer', 'NLSgpkgloader', 2)
            self.iface.messageBar().pushMessage("Error", "Failed to load the municipality layer", level=2, duration=5)
            return
        self.municipality_layer.setProviderEncoding('ISO-8859-1')
        self.utm5_layer = QgsVectorLayer(os.path.join(self.path, "data/utm5.shp"), "utm5", "ogr")
        if not self.utm5_layer.isValid():
            QgsMessageLog.logMessage('Failed to load the UTM 5 grid layer', 'NLSgpkgloader', 2)
            self.iface.messageBar().pushMessage("Error", "Failed to load the UTM 5 grid layer", level=2, duration=5)
            return
        self.utm10_layer = QgsVectorLayer(os.path.join(self.path, "data/utm10.shp"), "utm10", "ogr")
        if not self.utm10_layer.isValid():
            QgsMessageLog.logMessage('Failed to load the UTM 10 grid layer', 'NLSgpkgloader', 2)
            self.iface.messageBar().pushMessage("Error", "Failed to load the UTM 10 grid layer", level=2, duration=5)
            return
        self.utm25lr_layer = QgsVectorLayer(os.path.join(self.path, "data/utm25LR.shp"), "utm25lr", "ogr")
        if not self.utm25lr_layer.isValid():
            QgsMessageLog.logMessage('Failed to load the UTM 25LR grid layer', 'NLSgpkgloader', 2)
            self.iface.messageBar().pushMessage("Error", "Failed to load the UTM 25LR grid layer", level=2, duration=5)
            return
        self.utm25_layer = QgsVectorLayer(os.path.join(self.path, "data/utm25.shp"), "utm25", "ogr")
        if not self.utm25_layer.isValid():
            QgsMessageLog.logMessage('Failed to load the UTM 25 grid layer', 'NLSgpkgloader', 2)
            self.iface.messageBar().pushMessage("Error", "Failed to load the UTM 25 grid layer", level=2, duration=5)
            return
        self.utm50_layer = QgsVectorLayer(os.path.join(self.path, "data/utm50.shp"), "utm50", "ogr")
        if not self.utm50_layer.isValid():
            QgsMessageLog.logMessage('Failed to load the UTM 50 grid layer', 'NLSgpkgloader', 2)
            self.iface.messageBar().pushMessage("Error", "Failed to load the UTM 50 grid layer", level=2, duration=5)
            return
        self.utm100_layer = QgsVectorLayer(os.path.join(self.path, "data/utm100.shp"), "utm100", "ogr")
        if not self.utm100_layer.isValid():
            QgsMessageLog.logMessage('Failed to load the UTM 100 grid layer', 'NLSgpkgloader', 2)
            self.iface.messageBar().pushMessage("Error", "Failed to load the UTM 100 grid layer", level=2, duration=5)
            return
        self.utm200_layer = QgsVectorLayer(os.path.join(self.path, "data/utm200.shp"), "utm200", "ogr")
        if not self.utm200_layer.isValid():
            QgsMessageLog.logMessage('Failed to load the UTM 200 grid layer', 'NLSgpkgloader', 2)
            self.iface.messageBar().pushMessage("Error", "Failed to load the UTM 200 grid layer", level=2, duration=5)
            return

        self.instance = QgsProject.instance()

        if self.showUTMGridsAsLayer:
            found_utm5_layer = False
            found_utm10_layer = False
            found_utm25lr_layer = False
            found_utm25_layer = False
            found_utm50_layer = False
            found_utm100_layer = False
            found_utm200_layer = False
            current_layers = self.instance.layerTreeRoot().children()
            for current_layer in current_layers:
                if current_layer.layer().name() == "utm5":
                    found_utm5_layer = True
                    self.utm5_layer = current_layer.layer()
                if current_layer.layer().name() == "utm10":
                    found_utm10_layer = True
                    self.utm10_layer = current_layer.layer()
                if current_layer.layer().name() == "utm25lr":
                    found_utm25lr_layer = True
                    self.utm25lr_layer = current_layer.layer()
                if current_layer.layer().name() == "utm25":
                    found_utm25_layer = True
                    self.utm25_layer = current_layer.layer()
                if current_layer.layer().name() == "utm50":
                    found_utm50_layer = True
                    self.utm50_layer = current_layer.layer()
                if current_layer.layer().name() == "utm100":
                    found_utm100_layer = True
                    self.utm100_layer = current_layer.layer()
                if current_layer.layer().name() == "utm200":
                    found_utm200_layer = True
                    self.utm200_layer = current_layer.layer()
            if not found_utm200_layer:
                self.instance.addMapLayer(self.utm200_layer)
            if not found_utm100_layer:
                self.instance.addMapLayer(self.utm100_layer)
            if not found_utm50_layer:
                self.instance.addMapLayer(self.utm50_layer)
            if not found_utm25_layer:
                self.instance.addMapLayer(self.utm25_layer)
            if not found_utm25lr_layer:
                self.instance.addMapLayer(self.utm25lr_layer)
            if not found_utm10_layer:
                self.instance.addMapLayer(self.utm10_layer)
            if not found_utm5_layer:
                self.instance.addMapLayer(self.utm5_layer)

        if self.showMunicipalitiesAsLayer:
            found_layer = False
            current_layers = self.instance.layerTreeRoot().children()
            for current_layer in current_layers:
                if current_layer.layer().name() == "municipalities":
                    found_layer = True
                    self.municipality_layer = current_layer.layer()
                    break
            if not found_layer:
                self.instance.addMapLayer(self.municipality_layer)

    def getMunicipalityIntersectingFeatures(self, selected_mun_names, layer):
        intersecting_features = []

        expression = ''
        for mun in selected_mun_names:
            expression += u'"NAMEFIN" = \'' + mun + u'\' OR '
        expression = expression[:-4]
        #QgsMessageLog.logMessage("featureExpression: " + expression, 'NLSgpkgloader', 0)

        request = QgsFeatureRequest().setFilterExpression(expression)
        #request = QgsFeatureRequest().setFilterExpression(u'"NAMEFIN" = \'' + selected_mun_name + u'\'')
        #QgsMessageLog.logMessage("in getMunicipalityIntersectingFeatures", 'NLSgpkgloader', 0)
        iter = self.municipality_layer.getFeatures(request)
        count = 0
        for feature in iter:
            #QgsMessageLog.logMessage(str(count), 'NLSgpkgloader', 0)
            count += 1
            mun_geom = feature.geometry()

            layer_iter = layer.getFeatures()
            for layer_feature in layer_iter:
                layer_geom = layer_feature.geometry()
                if mun_geom.intersects(layer_geom):
                    intersecting_features.append(layer_feature)

        if not count: # TODO: check for duplicate map tiles in intersecting_features later
            # allow users to select municipalities both from list and on map
            iter = self.municipality_layer.selectedFeatures()
            for feature in iter:
                count += 1
                mun_geom = feature.geometry()
                layer_iter = layer.getFeatures()
                for layer_feature in layer_iter:
                    layer_geom = layer_feature.geometry()
                    if mun_geom.intersects(layer_geom):
                        intersecting_features.append(layer_feature)

        QgsMessageLog.logMessage("Number of municipalities found: " + str(count), 'NLSgpkgloader', 0)
        QgsMessageLog.logMessage("Count of " + layer.name() + " sheets (features) intersecting with the municipality: " + str(len(intersecting_features)), 'NLSgpkgloader', 0)

        return intersecting_features

    def downloadData(self, product_types):

        QgsMessageLog.logMessage("in downloadData", 'NLSgpkgloader', 0)

        self.all_urls = []
        self.total_download_count = 0
        self.download_count = 0
        self.layers_added_count = 0

        for product_key, product_title in list(product_types.items()):
            urls = self.createDownloadURLS(product_key, product_title)
            self.all_urls.extend(urls)
            self.total_download_count += len(urls)

        percentage = self.download_count / float(self.total_download_count) * 100.0
        percentage_text = "%.2f" % round(percentage, 2)

        QgsMessageLog.logMessage("A moment... downloaded " + percentage_text + "% of the files", 'NLSgpkgloader', 0)
        #QgsMessageLog.logMessage(str(self.total_download_count), 'NLSgpkgloader', 0)

        QTimer.singleShot(1000, self.downloadOneFile)

    def downloadNLSProductTypes(self):
        products = {}

        url = "https://tiedostopalvelu.maanmittauslaitos.fi/tp/feed/mtp?api_key=" + self.nls_user_key
        # TODO: use qgis.gui.QgsFileDownloader?
        r = requests.get(url)

        e = xml.etree.ElementTree.fromstring(r.text)

        for entry in e.findall('{http://www.w3.org/2005/Atom}entry'):
            title = entry.find('{http://www.w3.org/2005/Atom}title')
            QgsMessageLog.logMessage(title.text, 'NLSgpkgloader', 0)
            id = entry.find('{http://www.w3.org/2005/Atom}id')
            QgsMessageLog.logMessage(id.text, 'NLSgpkgloader', 0)

            if title.text == 'Maastotietokanta, kaikki kohteet':
                # TODO let user choose in the options dialog if the individual layers can be selected
                for mtk_product_name in MTK_PRODUCT_NAMES:
                    products[MTK_LAYERS_KEY_PREFIX + mtk_product_name] = MTK_PRODUCT_NAMES_PREFIX + mtk_product_name
            else:
                # products[id.text] = title.text
                pass

        return products

    def downloadOneFile(self):
        if self.download_count == self.total_download_count or self.download_count >= len(self.all_urls):
            QgsMessageLog.logMessage("Should not be possible to be here", 'NLSgpkgloader', 2)
            QgsMessageLog.logMessage("self.download_count: " + str(self.download_count), 'NLSgpkgloader', 0)
            QgsMessageLog.logMessage("Total download count: " + str(self.total_download_count), 'NLSgpkgloader', 0)
            self.busy_indicator_dialog.hide()
            return

        url = self.all_urls[self.download_count][0]
        QgsMessageLog.logMessage(url, 'NLSgpkgloader', 0)
        r = requests.get(url, stream=True)
        # TODO check r.status_code & r.ok

        url_parts = url.split('/')
        file_name = url_parts[-1].split('?')[0]

        data_dir_name = self.all_urls[self.download_count][1]
        data_dir_name = data_dir_name.replace(":", "_suhde_")
        dir_path = os.path.join(self.data_download_dir, data_dir_name)

        #QgsMessageLog.logMessage(dir_path, 'NLSgpkgloader', 0)
        if not os.path.exists(dir_path):
            try:
                os.makedirs(dir_path)
            except OSError as exc:
                QgsMessageLog.logMessage(str(exc.errno), 'NLSgpkgloader', 2)
        if not os.path.exists(dir_path):
            QgsMessageLog.logMessage("dir not created", 'NLSgpkgloader', 2)

        # TODO: don't keep zipfiles
        #z = zipfile.ZipFile(StringIO.StringIO(r.content))
        #z.extractall(os.path.join(self.data_download_dir, value))
        with open(os.path.join(dir_path, file_name), 'wb') as f:
            f.write(r.content)

        if "zip" in file_name:
            dir_path = os.path.join(dir_path, file_name.split('.')[0])
            z = zipfile.ZipFile(io.BytesIO(r.content))
            z.extractall(dir_path)

        self.download_count += 1
        percentage = self.download_count / float(self.total_download_count) * 100.0
        percentage_text = "%.2f" % round(percentage, 2)

        self.busy_indicator_dialog.setMessage(self.tr(u'A moment... downloaded ') + percentage_text + self.tr(u'% of the files '))

        QgsMessageLog.logMessage("A moment... downloaded " + percentage_text + "% of the files", 'NLSgpkgloader', 0)

        if self.download_count == self.total_download_count:
            QgsMessageLog.logMessage("done downloading data", 'NLSgpkgloader', 0)
            #self.busy_indicator_dialog.hide()
            self.createGeoPackage()
        else:
            QTimer.singleShot(10, self.downloadOneFile)

    def createGeoPackage(self):
        '''Creates a GeoPackage from the downloaded MTK data'''

        #self.busy_indicator_dialog = QgsBusyIndicatorDialog(self.tr(u'Processed 0% of the files '), self.iface.mainWindow())
        #self.busy_indicator_dialog.show()
        gpkg_path = os.path.join(self.data_download_dir, self.fileName)

        for dlIndex in range(0, self.total_download_count):

            url = self.all_urls[dlIndex][0]
            url_parts = url.split('/')
            file_name = url_parts[-1].split('?')[0]
            data_dir_name = self.all_urls[dlIndex][1]
            data_dir_name = data_dir_name.replace(":", "_suhde_")
            dir_path = os.path.join(self.data_download_dir, data_dir_name)
            dir_path = os.path.join(dir_path, file_name.split('.')[0])
            data_type = self.all_urls[dlIndex][3]

            for listed_file_name in os.listdir(dir_path):
                if data_type == "gml" and listed_file_name.endswith(".xml"):
                    driver = ogr.GetDriverByName('GML')
                    data_source = driver.Open(os.path.join(dir_path, listed_file_name), 0)
                    layer_count = data_source.GetLayerCount()

                    mtk_layer_count = 0 # Used for breaking from the for loop when all MTK layers chosen by the user have been added

                    for i in range(layer_count):
                        layer = data_source.GetLayerByIndex(i)
                        layer_name = layer.GetName()

                        if url.startswith(MTK_ALL_PRODUCTS_DOWNLOAD_URL):
                            for product_type in self.selected_mtk_product_types:
                                if product_type == layer_name:
                                    new_layer = QgsVectorLayer(os.path.join(dir_path, listed_file_name) + "|layerid=" + str(i), layer_name, "ogr")

                                    if new_layer.isValid():
                                        options = QgsVectorFileWriter.SaveVectorOptions()
                                        options.layerName = layer_name
                                        options.driverName = "GPKG"
                                        options.fileEncoding = "UTF-8"

                                        if self.newFile: # TODO: ask for confirmation on overwrite
                                            options.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteFile
                                            self.newFile = False
                                        elif QgsVectorLayer(gpkg_path + "|layername=" + layer_name).isValid():
                                            options.actionOnExistingFile = QgsVectorFileWriter.AppendToLayerNoNewFields
                                        else:
                                            options.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteLayer

                                        e = QgsVectorFileWriter.writeAsVectorFormat(new_layer, gpkg_path, options)
                                        if e[0]:
                                            QgsMessageLog.logMessage("Failed to write layer " + layer_name + " to geopackage", 'NLSgpkgloader', 2)
                                            break
                                        else:
                                            QgsMessageLog.logMessage("Finished writing GeoPackage", 'NLSgokgloader', 0)
                                        # self.instance.addMapLayer(new_layer)
                                        mtk_layer_count += 1
                                    else:
                                        # TODO: handle invalid layer error
                                        #QgsMessageLog.logMessage("Invalid layer: " + listed_file_name + ":" layer_name, 'NLSgpkgloader', 2)
                                        pass
                                    break
                        else:
                            QgsMessageLog.logMessage("Download URL doesn't start with MTK_ALL_PRODUCTS_DOWNLOAD_URL", 'NLSgpkgloader', 2)
                            # new_layer = QgsVectorLayer(os.path.join(dir_path, listed_file_name) + "|layerid=" + str(i), layer_name, "ogr")
                            # if new_layer.isValid():
                            #     self.instance.addMapLayer(new_layer)

                        if (url.startswith(MTK_ALL_PRODUCTS_DOWNLOAD_URL) and mtk_layer_count == len(self.selected_mtk_product_types)):
                            break
                else:
                    QgsMessageLog.logMessage("cannot add the data type " + data_type + ", listed_file_name: " + listed_file_name, 'NLSgpkgloader', 0)

        conn = ogr.Open(gpkg_path)
        for i in conn:
            params = {
                'INPUT': gpkg_path + "|layername=" + i.GetName(),
                'FIELD': ['gid'],
                'OUTPUT': 'ogr:dbname=\'' + gpkg_path + '\' table=\"' + i.GetName() + '_dissolved\" (geom) sql='
            }
            processing.run("native:dissolve", params)

            percentage = dlIndex/float(self.total_download_count) * 100.0
            percentage_text = "%.2f" % round(percentage, 2)
            self.busy_indicator_dialog.setMessage(self.tr(u'Processed ') + percentage_text + self.tr(u'% of the files'))

            if self.addDownloadedDataAsLayer:
                self.instance.addMapLayer(QgsVectorLayer(gpkg_path+ "|layername=" + i.GetName() + "_dissolved", i.GetName()))

        self.busy_indicator_dialog.hide()
        self.iface.messageBar().pushMessage(self.tr(u'Download finished'), \
            self.tr(u'NLS data download finished. Data located under ') + \
            gpkg_path, level=3)

    def showSettingsDialog(self):
        self.nls_user_key_dialog.dataLocationQgsFileWidget.setStorageMode(QgsFileWidget.GetDirectory)

        self.nls_user_key_dialog.userKeyLineEdit.setText(self.nls_user_key)
        self.nls_user_key_dialog.dataLocationQgsFileWidget.setFilePath(QSettings().value("/NLSgpkgloader/dataDownloadDir", os.path.join(self.path, "data"), type=str))
        self.nls_user_key_dialog.addDownloadedDataAsLayerCheckBox.setChecked(self.addDownloadedDataAsLayer)
        self.nls_user_key_dialog.showMunicipalitiesAsLayerCheckBox.setChecked(self.showMunicipalitiesAsLayer)
        self.nls_user_key_dialog.showUTMGridsAsLayerCheckBox.setChecked(self.showUTMGridsAsLayer)

        self.nls_user_key_dialog.show()

        # Run the dialog event loop
        result = self.nls_user_key_dialog.exec_()
        # See if OK was pressed
        if result:
            self.nls_user_key = self.nls_user_key_dialog.userKeyLineEdit.text().strip()
            if self.nls_user_key == "":
                # cannot work without the key, so user needs to be notified
                QMessageBox.critical(self.iface.mainWindow(), self.tr(u'User-key is needed'), self.tr(u'Data cannot be downloaded without the NLS key'))
                return
            self.data_download_dir = self.nls_user_key_dialog.dataLocationQgsFileWidget.filePath()
            self.addDownloadedDataAsLayer = self.nls_user_key_dialog.addDownloadedDataAsLayerCheckBox.isChecked()
            self.showMunicipalitiesAsLayer = self.nls_user_key_dialog.showMunicipalitiesAsLayerCheckBox.isChecked()
            self.showUTMGridsAsLayer = self.nls_user_key_dialog.showUTMGridsAsLayerCheckBox.isChecked()

            if self.showMunicipalitiesAsLayer or self.showUTMGridsAsLayer:
                self.loadLayers()
            # TODO: else: unloadLayers()

            QSettings().setValue("/NLSgpkgloader/userKey", self.nls_user_key)
            QSettings().setValue("/NLSgpkgloader/dataDownloadDir", self.data_download_dir)
            QSettings().setValue("/NLSgpkgloader/addDownloadedDataAsLayer", self.addDownloadedDataAsLayer)
            QSettings().setValue("/NLSgpkgloader/showMunicipalitiesAsLayer", self.showMunicipalitiesAsLayer)
            QSettings().setValue("/NLSgpkgloader/showUTMGridsAsLayer", self.showUTMGridsAsLayer)

        else:
            if self.nls_user_key == "":
                # cannot work without the key, so user needs to be notified
                QMessageBox.critical(self.iface.mainWindow(), self.tr(u'User-key is needed'), self.tr(u'Data cannot be downloaded without the NLS key'))
                return

    def initWithNLSData(self):
        self.path = os.path.dirname(__file__)
        self.data_download_dir = self.path
        #self.gpkg_dir = "/tmp/result.gpkg" # TODO: make this modifiable by the user

        self.nls_user_key_dialog = uic.loadUi(os.path.join(self.path, NLS_USER_KEY_DIALOG_FILE))
        self.first_run = QSettings().value("/NLSgpkgloader/first_run", True, type=bool)
        if self.first_run:
            QSettings().setValue("/NLSgpkgloader/first_run", False)

    def createDownloadURLS(self, product_key, product_title):

        urls = []

        if product_key == "https://tiedostopalvelu.maanmittauslaitos.fi/tp/feed/mtp/maastotietokanta/kaikki":
            urls = self.createTopographicDatabaseDownloadURLS(product_key, product_title)
        else:
            QgsMessageLog.logMessage('Unknown product ' + product_title +  ', please send error report to the author', 'NLSgpkgloader', 2)
            self.iface.messageBar().pushMessage('Unknown product ' + product_title +  ', please send error report to the author', level=2, duration=10)

        #QgsMessageLog.logMessage("URL count: " + str(len(urls)), 'NLSgpkgloader', 0)
        return urls

    def createTopographicDatabaseDownloadURLS(self, product_key, product_title):

        urls = []

        for mun_utm_feature in self.mun_utm25lr_features:
            sheet_name = mun_utm_feature['LEHTITUNNU']
            sn1 = sheet_name[:2]
            sn2 = sheet_name[:3]
            #https://tiedostopalvelu.maanmittauslaitos.fi/tp/tilauslataus/tuotteet/maastotietokanta/kaikki/etrs89/gml/L4/L41/L4134L_mtk.zip?token=vk2mphnnvbtrp313ee4amjpo2o
            modified_key = product_key.replace("/feed/mtp", "/tilauslataus/tuotteet")

            url = modified_key + "/etrs89/gml/" + sn1 + "/" + sn2 + "/" + sheet_name + "_mtk.zip?api_key="  + self.nls_user_key
            #QgsMessageLog.logMessage(url, 'NLSgpkgloader', 0)

            urls.append((url, product_title, product_key, "gml"))

        return urls
